# Generated by Django 4.0.4 on 2022-04-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=100)),
                ('all_repos', models.SmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
